# Generated by Django 5.2.3 on 2025-07-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departedmember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='departedmember',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='departedmember',
            name='date_of_passing',
        ),
        migrations.RemoveField(
            model_name='departedmember',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tribute',
            name='approved',
        ),
        migrations.AlterField(
            model_name='departedmember',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
