SHIRT_SIZES = [
            ('S', 'Small (S)'),
            ('M', 'Medium (M)'),
            ('L', 'Large (L)'),
            ('XL', 'Extra Large (XL)'),
            ('XXL', 'Double Extra Large (XXL)'),
        ]


CURRENCY_CHOICES = [
    ("USD", "US Dollar (USD)"),
    ("EUR", "Euro (EUR)"),
    ("GBP", "British Pound (GBP)"),
    ("NGN", "Nigerian Naira (NGN)"),
    ("KES", "Kenyan Shilling (KES)"),
    ("ZAR", "South African Rand (ZAR)"),
    ("GHS", "Ghanaian Cedi (GHS)"),
    ("CAD", "Canadian Dollar (CAD)"),
    ("AUD", "Australian Dollar (AUD)"),
    ("JPY", "Japanese Yen (JPY)"),
    ("CNY", "Chinese Yuan (CNY)"),
    ("INR", "Indian Rupee (INR)"),
    ("BRL", "Brazilian Real (BRL)"),
    ("MXN", "Mexican Peso (MXN)"),
    ("CHF", "Swiss Franc (CHF)"),
    ("SEK", "Swedish Krona (SEK)"),
    ("NOK", "Norwegian Krone (NOK)"),
    ("DKK", "Danish Krone (DKK)"),
    ("AED", "UAE Dirham (AED)"),
    ("SAR", "Saudi Riyal (SAR)"),
    ("EGP", "Egyptian Pound (EGP)"),
    ("TZS", "Tanzanian Shilling (TZS)"),
    ("UGX", "Ugandan Shilling (UGX)"),
    ("XOF", "West African CFA franc (XOF)"),
    ("XAF", "Central African CFA franc (XAF)"),
    ("RUB", "Russian Ruble (RUB)"),
    ("KRW", "South Korean Won (KRW)"),
    ("SGD", "Singapore Dollar (SGD)"),
    ("HKD", "Hong Kong Dollar (HKD)"),
    ("NZD", "New Zealand Dollar (NZD)"),
]