# Generated by Django 5.2.3 on 2025-07-05 16:32

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('shirt_size', models.CharField(choices=[('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'Double Extra Large (XXL)')], default='M', max_length=10)),
                ('gift1', models.URLField(blank=True, null=True)),
                ('gift2', models.URLField(blank=True, null=True)),
                ('gift3', models.URLField(blank=True, null=True)),
                ('gift4', models.URLField(blank=True, null=True)),
                ('donation_currency', models.CharField(blank=True, choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('NGN', 'Nigerian Naira (NGN)'), ('KES', 'Kenyan Shilling (KES)'), ('ZAR', 'South African Rand (ZAR)'), ('GHS', 'Ghanaian Cedi (GHS)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)'), ('JPY', 'Japanese Yen (JPY)'), ('CNY', 'Chinese Yuan (CNY)'), ('INR', 'Indian Rupee (INR)'), ('BRL', 'Brazilian Real (BRL)'), ('MXN', 'Mexican Peso (MXN)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (SEK)'), ('NOK', 'Norwegian Krone (NOK)'), ('DKK', 'Danish Krone (DKK)'), ('AED', 'UAE Dirham (AED)'), ('SAR', 'Saudi Riyal (SAR)'), ('EGP', 'Egyptian Pound (EGP)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('UGX', 'Ugandan Shilling (UGX)'), ('XOF', 'West African CFA franc (XOF)'), ('XAF', 'Central African CFA franc (XAF)'), ('RUB', 'Russian Ruble (RUB)'), ('KRW', 'South Korean Won (KRW)'), ('SGD', 'Singapore Dollar (SGD)'), ('HKD', 'Hong Kong Dollar (HKD)'), ('NZD', 'New Zealand Dollar (NZD)')], max_length=3, null=True)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
        ),
    ]
